export const YDB_DRIVER = Symbol('YDB_DRIVER');
export const YDB_QUERY = Symbol('YDB_QUERY');
export const YDB_OPTIONS = Symbol('YDB_OPTIONS');
export const YDB_CREDENTIALS_PROVIDER = Symbol('YDB_CREDENTIALS_PROVIDER');
export const YDB_ENCRYPTION_PROVIDER = Symbol('YDB_ENCRYPTION_PROVIDER');
export const YDB_BLIND_INDEX_PROVIDER = Symbol('YDB_BLIND_INDEX_PROVIDER');
export const YDB_SCHEMA_SYNC = Symbol('YDB_SCHEMA_SYNC');
